# This docker compose is meant for dev and demo proposes
# services are directly accessible through their ports

version: "3.7"

x-backend: &backend
  build: .
  environment:
    - POSTGRES_HOST=db
    - POSTGRES_DB=internal
    - POSTGRES_PASSWORD=postgres

services:
  db:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=internal
      - POSTGRES_PASSWORD=postgres

  alembic:
    <<: *backend
    depends_on:
      - db
    command: alembic upgrade head

  api:
    <<: *backend
    depends_on:
      - alembic
      - db
    ports:
    - '8000:8000'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`localhost`)"
      - "traefik.http.routers.whoami.entrypoints=web"

  traefik:
    image: "traefik:v2.5"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
